name: CI/CD Pipeline - Train ML Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  github-actions-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r M3/requirements.txt
          pip install flake8  
      
      - name: Lint code
        run: |
          flake8 . --max-line-length=79 

      - name: Train Model
        run: |
          python M1/training2.py

      - name: Verify Model Exists
        run: |
          ls -l M1/model2.joblib

      - name: Run Tests
        run: |
          pytest M1/test_model.py
        
    